# -*- coding: utf-8 -*-
"""CipraTakeHomeassignment2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15dtfU4LiYAMhgt60jQGCsORTrJ0w3JEg
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import Pipeline
from sklearn.metrics import roc_auc_score, accuracy_score

url = "https://raw.githubusercontent.com/vibha300/Cipra/main/mock_ppg_dataset.csv"
df = pd.read_csv(url)

df.columns = ["id", "signal", "label"]

import numpy as np
import tensorflow as tf

# Encode labels
label_map = {"clean": 0, "noisy": 1}
df["y"] = df["label"].map(label_map)

X = np.stack(df["signal"].apply(np.array).values)  # (N, signal_len)
y = df["y"].values.astype(np.float32)

import numpy as np

def parse_signal(s):
    return np.array([float(x) for x in s.split()])

df["signal_vec"] = df["signal"].apply(parse_signal)

df["signal_vec"]

row = df["signal_vec"].iloc[0]
print(type(row))
print(row.shape)
print(row[:10])

X = np.stack(df["signal_vec"].values)
print(X.shape)

WINDOW = 10

def make_windows(X, y, window):
    Xw, yw = [], []
    for t in range(window, len(X)):
        Xw.append(X[t-window:t])  # (W, signal_len)
        yw.append(y[t])
    return np.array(Xw), np.array(yw)

Xw, yw = make_windows(X, y, WINDOW)

print(Xw.shape)  # (num_samples, W, signal_len)

split = int(0.8 * len(Xw))

X_train, X_val = Xw[:split], Xw[split:]
y_train, y_val = yw[:split], yw[split:]

class PositionalEncoding(tf.keras.layers.Layer):
    def __init__(self, d_model, max_len=500):
        super().__init__()
        pos = np.arange(max_len)[:, None]
        i = np.arange(d_model)[None, :]
        angle_rates = 1 / np.power(10000, (2 * (i // 2)) / np.float32(d_model))
        angle_rads = pos * angle_rates

        pe = np.zeros((max_len, d_model))
        pe[:, 0::2] = np.sin(angle_rads[:, 0::2])
        pe[:, 1::2] = np.cos(angle_rads[:, 1::2])
        self.pe = tf.constant(pe, dtype=tf.float32)

    def call(self, x):
        return x + self.pe[: tf.shape(x)[1]]

class TransformerBlock(tf.keras.layers.Layer):
    def __init__(self, d_model, num_heads, dff, rate=0.1):
        super().__init__()
        self.att = tf.keras.layers.MultiHeadAttention(
            num_heads=num_heads, key_dim=d_model
        )
        self.ffn = tf.keras.Sequential([
            tf.keras.layers.Dense(dff, activation="relu"),
            tf.keras.layers.Dense(d_model)
        ])
        self.layernorm1 = tf.keras.layers.LayerNormalization(epsilon=1e-6)
        self.layernorm2 = tf.keras.layers.LayerNormalization(epsilon=1e-6)
        self.dropout1 = tf.keras.layers.Dropout(rate)
        self.dropout2 = tf.keras.layers.Dropout(rate)

    def call(self, x, training=None):
        attn_output = self.att(x, x)
        attn_output = self.dropout1(attn_output, training=training)
        out1 = self.layernorm1(x + attn_output)

        ffn_output = self.ffn(out1)
        ffn_output = self.dropout2(ffn_output, training=training)
        return self.layernorm2(out1 + ffn_output)

def build_model(signal_len, window, d_model=128, num_heads=4, num_layers=2):
    inputs = tf.keras.Input(shape=(window, signal_len))

    # Project each segment to embedding
    x = tf.keras.layers.Dense(d_model)(inputs)

    # Add temporal position
    x = PositionalEncoding(d_model)(x)

    # Transformer layers
    for _ in range(num_layers):
        x = TransformerBlock(d_model, num_heads, dff=4*d_model)(x)

    # Use last time step for prediction
    x = tf.keras.layers.Lambda(lambda t: t[:, -1])(x)

    outputs = tf.keras.layers.Dense(1, activation="sigmoid")(x)

    return tf.keras.Model(inputs, outputs)

model = build_model(
    signal_len=X.shape[1],
    window=WINDOW
)

model.compile(
    optimizer=tf.keras.optimizers.Adam(1e-3),
    loss="binary_crossentropy",
    metrics=["accuracy", tf.keras.metrics.AUC(name="auc")]
)

model.summary()

history = model.fit(
    X_train,
    y_train,
    validation_data=(X_val, y_val),
    epochs=15,
    batch_size=32
)

p_noise = model.predict(Xw)

# Smooth probability over time
p_noise_smooth = np.convolve(
    p_noise.squeeze(),
    np.ones(5)/5,
    mode="same"
)

t = np.arange(len(p_noise))
y_aligned = y[WINDOW:]

import matplotlib.pyplot as plt

plt.figure(figsize=(12, 4))

plt.plot(t, p_noise.squeeze(),
         label="P(noisy) – model",
         color="tab:blue", alpha=0.6)

plt.plot(t, p_noise_smooth,
         label="P(noisy) – smoothed",
         color="tab:red", linewidth=2)

plt.step(t, y_aligned,
         where="post",
         label="True label (clean/noisy)",
         color="black", alpha=0.4)

plt.ylim(-0.05, 1.05)
plt.xlabel("Time (segments)")
plt.ylabel("Noise probability")
plt.title("Temporal Noise Probability Trajectory")
plt.legend()
plt.tight_layout()
plt.show()

# Static baseline: classify each segment independently
y_static = (p_noise.squeeze() > 0.5).astype(int)

plt.figure(figsize=(12, 3))
plt.step(t, y_static, label="Static prediction", alpha=0.6)
plt.step(t, y_aligned, label="True label", alpha=0.6)
plt.legend()
plt.title("Static vs Temporal Predictions")
plt.show()

threshold = 0.5
change_points = np.where(np.diff(p_noise_smooth > threshold))[0]

for cp in change_points:
    plt.axvline(cp, color="gray", linestyle="--", alpha=0.3)

plt.figure(figsize=(12, 4))

plt.plot(t, p_noise_smooth, label="Smoothed P(noisy)", linewidth=2)
plt.step(t, y_aligned, where="post", label="True label", alpha=0.3)

threshold = 0.5
change_points = np.where(np.diff(p_noise_smooth > threshold))[0]

for cp in change_points:
    plt.axvline(cp, color="gray", linestyle="--", alpha=0.3)

plt.axhline(threshold, color="red", linestyle=":", alpha=0.5)

plt.ylim(-0.05, 1.05)
plt.xlabel("Time (segments)")
plt.ylabel("Noise probability")
plt.title("Temporal Regimes and Change-Point Detection")
plt.legend()
plt.tight_layout()
plt.show()